
CREATE SEQUENCE USER_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PRODUCT_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE TB_USER
(
    id         BIGINT AUTO_INCREMENT PRIMARY KEY,
    name       VARCHAR(100)        ,
    last_name  VARCHAR(100)        ,
    email      VARCHAR(255) UNIQUE ,
    password   VARCHAR(255)        ,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    non_locked BOOLEAN   DEFAULT FALSE,
    enabled    BOOLEAN   DEFAULT TRUE
);

CREATE TABLE TB_PRODUCT
(
    id          BIGINT AUTO_INCREMENT PRIMARY KEY,
    name        VARCHAR(255)   NOT NULL,
    description TEXT,
    price       DECIMAL(10, 2) NOT NULL,
    user_id     BIGINT         NOT NULL,
    enabled     BOOLEAN        NOT NULL DEFAULT TRUE,
    quantity    NUMBER         NOT NULL DEFAULT 1
);